### ISSUE TITLE
Suggestion: "DOMContentLoaded" + Selectors should affect the JS

### ISSUE THREAD

**Issue by MBWebTechMariusz** [sampotts/rangetouch#10]
Hi,

I would like to use rangetouch only on specific input ranges. This makes sense if I just want to fix some of the range inputs, but not all of them.
Reason: I've added the plyr.io plugin in a site, but they've had some custom input ranges aswell. In order not to break these other modules, I wanted to have the fix only on my input ranges, which I have defined in the settings of rangetouch.

So, my sugesstions:
1. Add document.ready for setup (TBD: what happens with input which will initialized after the page has loaded, e.g. via AJAX?)
```
    document.addEventListener("DOMContentLoaded", function () {
        // Run setup automatically
        setup();
    });
```

2. Only fire the "set()" function if the range settings matches
```
-        if (!settings.enabled || event.target.type !== 'range' || isDisabled(event.target)) {
+        if (!settings.enabled || event.target.type !== 'range' || isDisabled(event.target) || !event.target.matches(settings.selectors.range)) {
            return;
        }
```

With this, you can setup the rangetouch via the settings:
```
        addCSS: true,
        thumbWidth: 15,
        selectors: {
-            range: '[type="range"]',
+            range: '.plyr-container [type="range"]',
            disabled: '.rangetouch--disabled'
        },
```
TBD: Shouldn't the selector/settings via constructor be configurable, so you can actually call the rangetouch plugin when you need it with special selectors?

**Comment by sampotts** [comment]
Hey, sorry for the delay. There's a new `v2.0.0-beta.1` that uses a proper ES6 class so must be setup per input. There's also a static `RangeTouch.setup()` method that allows you to setup multiple inputs and returns an array of the references to the instances so you can destroy them etc. I think this will improve support for frameworks like React where you can import the lib and setup RangeTouch in your component. Give it a go and give feedback if you can. I'm still testing myself (hence beta) so there may be bugs. 

Also, I may well just include the library into Plyr since I get a lot of feedback about that. I think it will be a very small include anyway.
