### ISSUE TITLE
Rangetouch and Material Design Light

### ISSUE THREAD

**Issue by kasperkamperman** [sampotts/rangetouch#4]
Hi,
I'm using [Material Design Light](https://getmdl.io) as a framework. However adding rangetouch to my code doesn't seem to have much effect on touch devices (in contrary of your own demo). 

Any idea what can be the cause? I've already added a bigger thumbwidth. 

My demo: http://dev.kasperkamperman.com/localremote/index.html

Code of the demo:
https://github.com/kasperkamperman/Particle-RGB-RemoteControl/tree/master/web-code/RGB%20CloudRemote

**Comment by ryancwalsh** [comment]
Rangetouch was working for me when I installed it on 2017-06-06 but then stopped working in recent days. My only touch devices are iOS (I don't own any Android so can't speak about those). Since Rangetouch code hasn't changed, and I don't think my code / server has changed, I wonder if something in iOS or those apps has changed that prevents Rangetouch from working. I don't know what Material Design Light is, but I figured my comment might be relevant for you anyway. I'm still investigating my problem.

**Comment by ryancwalsh** [comment]
@kasperkamperman I figured out my problem: https://github.com/sampotts/rangetouch/issues/5

**Comment by kasperkamperman** [comment]
@ryancwalsh Thanks for your note. I've checked your problem and then I've read the documentation page again. I noticed that I had to include the script at the end just before the body closing tag (I just added out of habit the script in the header). This did the trick.

**Comment by sampotts** [comment]
Thanks lads. I've made it a little cleaner code-wise now so you should be able to add this anywhere although of course, before the closing `</body>` is best but you can always use the `async` and `defer` attributes to decide how you want the script loaded.
